name: music_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.5.0
  google_fonts: ^4.0.3
  google_sign_in: ^6.2.1
  provider: ^6.0.0
  just_audio: ^0.9.42
  logger: ^2.6.2
  intl: ^0.19.0
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  webview_flutter: ^4.7.0
  crypto: ^3.0.3
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/logo/

  uses-material-design: true
  